### ISSUE TITLE
Multi-animal pose estimation and tracking with DeepLabCut

### ISSUE THREAD

**Issue by yj-song131** [GDSC-Ewha-4th/Study-paperReview#20]
Introduction
* 동물의 자세를 예측하는 것은 Computer Vision problem의 Challenge 중 하나이다.
* 이 논문에서는 자세 예측에서 유용한 오픈소스인 DeepLabCut을 이용한다.
* We illustrate the power of this framework with four datasets varying in complexity.

Architecture
* 새로운 DeepLabCut Architecture인 DLCRNet은 5개의 conv layer를 가지고 있다.
* keypoint에 따라 3개의 output layer를 만든다.
* benchmarking을 위해 현재의 architecture를 large-scale multi-human pose estimation인 COCO와 비교하였다.
   + 우리의 model은 COCO의 HigherHRNet( 69.8 vs 70.6 ) 에 비교되는 mAP를 가지고 있다.

**Comment by minha62** [comment]
동물의 자세를 예측하는 task는 생각해본적이 없었는데 흥미롭네요!
좋은 내용 감사합니다:)
