### ISSUE TITLE
Tidy Data

### ISSUE THREAD

**Issue by minha62** [GDSC-Ewha-4th/Study-paperReview#24]
## `Tidy Data`

1. 각 변수(variable)는 열을 구성
2. 각 관측치(observation)는 행을 구성
3. 각 cell은 single measurement
4. 각 표는 단 하나의 관측기준에 의해서 조직된 데이터를 저장
5. 만약 여러 개의 표가 존재한다면, 적어도 하나 이상의 열이 공유되어야 함

![image](https://user-images.githubusercontent.com/71062967/194739856-f94c102d-52b0-4efc-9375-b18af4fa8dd7.png)

| 관측치(Observation): 값을 측정한 단위.

변수가 키, 몸무게, 성별이었다면 관측치는 각각의 사람

---

### 1. 열 이름이 변수 이름이 아닌 값인 경우

- 왼쪽 데이터 테이블의 열을 보면 열 이름이 소득의 범위(값)로 분석 시 불편함 발생
    
    ➡ 분석하기 좋은 형태로 변경하면 오른쪽 데이터 테이블
 

![image](https://user-images.githubusercontent.com/71062967/194739861-453cd7bd-05dc-41d8-9b2b-65d6195b257c.png)

### 2. 같은 표에 다양한 관측 단위가 있는 경우

- **공통으로 묶을 수 있는 키**를 만들어줘야 함
    - 위에 있는 테이블을 보면 track, time, genre의 많은 관측값들이 중복
        
        ➡ 노래, 랭킹으로 구분하여 2개의 테이블로 나눔
        

![image](https://user-images.githubusercontent.com/71062967/194739868-8fb1d7bd-a8f0-4495-8d92-20e3177bb3ce.png)

### 3. 하나의 열에 여러 값이 들어있는 경우변수가 행과 열에 모두 포함되어 있는 경우

- 왼쪽 테이블의 열을 보면 많은 값들이 존재
    - 성별(”m” or “f”)
    - 연령 그룹(”0-14”, “15-24”, “25-34”, “45-54”, “55-64”, “65”, “알 수 없음”)
    - 결측치의 종류가 0과 결측값(”NaN”)으로 혼합되어 있음
    
    ➡ 서로 관계가 있고, 어떠한 구간으로 존재하기 때문에 이러한 데이터는 열이 아닌 행으로
    

![image](https://user-images.githubusercontent.com/71062967/194739876-bebe821f-ef71-4cf8-a2c3-74fdd5c7839b.png)

### 4. 변수가 행과 열에 모두 포함되어 있는 경우

- 왼쪽 테이블에서 d1~d8 데이터를 행으로 변경해서 오른쪽 테이블처럼 만들어줌
- 오른쪽 테이블을 보면 각각의 id당 element가 tmax, tmin 두 개의 값을 가짐
    - id, year, month은 값지만 element만 다른 값으로 존재 ➡ 열로 변경

![image](https://user-images.githubusercontent.com/71062967/194739880-b7a47546-f397-42e1-8686-4b956734b6da.png)

### 5. 하나의 관측 단위가 여러 파일로 나누어져 있는 경우

- 서로 다른 파일에 존재하는 데이터들을 합쳐주는 작업 필요

---

📌 Tidy Data가 중요한 이유는 **분석 시 편리함**과 **시각화**

---

참고)

[https://jaaamj.tistory.com/135](https://jaaamj.tistory.com/135)

[https://partrita.github.io/posts/tidy-data/#Pew-Research-Center-Dataset](https://partrita.github.io/posts/tidy-data/#Pew-Research-Center-Dataset)

**Comment by yj-song131** [comment]
Tidy Data의 개념과 중요성을 알게 되어서 흥미로웠습니다 😄 잘 읽었습니다!!
