### ISSUE TITLE
ADAM: A Method for Stochastic Optimization

### ISSUE THREAD

**Issue by jskim19** [GDSC-Ewha-4th/Study-paperReview#38]
### Abstract
Adam은 stochastic objective function을 first-order gradient-based로 optimize 하는 algorithm
계산이 효율적이고 non-stationary objective와 noisy한 것들에 적합 

### Introduction 
이 논문의 목표는 고차 함수의 stochastic objectives 의 최적화 (first-order methods)
적은 memory의 first-order gradients만을 요구하는 효율적인 stochastic optimization, AdaGrad와 RMSP의 장점을 합쳐서 디자인됨 

### Algorithm 
SNR이 작을수록 effective step size delta_t가 zero에 가까워짐 
effective step size는 gradient의 scale에 invariant 

### Related Work 
RMSprop, AdaGrad, SGD, AdaDelta, natural Newton method from Roux & Fitzgibbon 
SFO는 Adam 과는 다르게 memory required 
NGD와 유사하게 data의 geometry preconditioner 적용  
RMSProp은 rescaled gradient의 momentum을 사용해 변수들을 업데이트하지만, Adam은 1st and 2nd moment의running average로 directly estimated 

### Experiment 
Figure 1: SGD와 비슷한 수렴, Adagrad보다 빨리 수렴 
Standard deterministic cross-entropy objective function을 이용한 different optimizer 
CNN: 3 alternating stages of 5*5 convolution filters, 3*3 max pooling with stride of 2 
slow decay 하는 케이스에서 optimization의 adverse effect을 막기 위해서는 bias correction term이 중요

**Comment by minha62** [comment]
잘 읽었습니다! 좋은 내용 감사합니다:)

**Comment by charlottejruby** [comment]
알고리즘의 방향성에 대해 간략히 읽고 궁금해져서 다음에 같은 논문 읽어보겠습니다. 좋은 내용 감사합니다.
