### ISSUE TITLE
U-Net: Convolutional Networks for Biomedical Image Segmentation

### ISSUE THREAD

**Issue by minha62** [GDSC-Ewha-4th/Study-paperReview#42]
`U-Net`
: 의생명 분야에서 이미지 분할을 하기 위해 제안된 End-to-End, Fully-Convolutional Network 기반 모델
- FCNs보다 확장된 개념의 Up-sampling과 Skip architecture를 적용한 모델 제안
➡ 아주 적은 학습 데이터로도 data augmentation을 활용하여 우수한 성능

![image](https://user-images.githubusercontent.com/71062967/200175616-2f26121a-b127-44cc-92d4-f75042ef9e3f.png)

네트워크 구조가 U 모양으로 생겨서 U-Net이라고 부른다.

<br>

---

### U-Net은 두 네트워크가 대칭 형태

1. 입력 이미지의 **context 정보**를 얻기 위한 네트워크
   - FCNs처럼 VGG 기반 구조
   - padding 없이 3x3 Conv 2차례씩 반복
   - 활성화 함수: ReLU
   - 2x2 Max-pooling / stride=2
   - Down-sampling마다 채널 수를 2배로 늘림
![image](https://user-images.githubusercontent.com/71062967/200176808-89de45ce-754b-4dcd-b2e7-ecbc41f7a74d.png)

<br>

2. **정확한 localization**을 위한 네트워크
   - Contracting path의 최종 특징 맵으로부터 보다 높은 해상의 segmentation 결과를 얻기 위해 Up-sampling 여러 차례 진행
      - 즉, coarse map에서 dense prediction을 얻기 위한 구조
   - Contracting path와 반대 연산으로 특징 맵 확장
      - 2x2 Conv (Up-Convolution)
      - padding 없이 3x3 Conv 2차례씩 반복
      - Up-Conv를 통한 Up-samlping마다 채널의 수를 반으로 줄임
      - 활성화 함수: ReLU
      - Up-Conv된 특징 맵은 Contracting path의 테두리가 cropped된 특징 맵과 concatenation
      - 마지막 레이어에 1x1 Conv
   
![image](https://user-images.githubusercontent.com/71062967/200176813-a3e7ec83-a190-401b-8822-fec87e9f4a36.png)
![image](https://user-images.githubusercontent.com/71062967/200177662-141e17a1-2d04-44d3-b40c-8dff8d83f1f0.png)

<br>

- Coarse Map to Dense Map + FCN's skip architecture를 활용하여 얕은 층의 특징 맵을 깊은 층의 특징 맵과 결합했다.
➡ CNN Network의 feature hierarchy 결합을 통해 segmentation이 내제하는 `localization`과 `context(semantic information)` 간 trade-off 해결 가능

- 총 23 레이어의 Fully Convolutional Networks 구조

> 최종 출력인 Segmentation map의 크기는 입력 이미지 크기보다 작다. 이는 Convolution 연산에서 padding을 사용하지 않았기 때문!

---

### Ovelap-Tite Input

Fully Convolutional Network 구조 특성 상 입력 이미지는 크기에 제약을 받지 않는다.
➡ 큰 사이즈의 이미지는 전체를 사용하지 않고 `overlap-tite`!

![image](https://user-images.githubusercontent.com/71062967/200177994-5dd11dc8-e9be-4c73-b245-cd0b49fef503.png)

- 이미지를 tile(patch)로 나눠서 input으로 사용
- 파란색 영역의 이미지를 입력하면 노란색 영역의 segmentation 결과
- 다음 tile에 대한 segmentation을 얻기 위해선 이전 input의 일부분이 포함되어야 한다.
- 이미지의 경계 부분 픽셀에 대한 segmentation은 0이나 임의의 패딩값을 사용하는 것이 아닌, 이미지 경계 부분의 미러링을 이용한 Extrapolation을 사용한다.

---
참고)
[U-Net 논문 리뷰](https://medium.com/@msmapark2/u-net-%EB%85%BC%EB%AC%B8-%EB%A6%AC%EB%B7%B0-u-net-convolutional-networks-for-biomedical-image-segmentation-456d6901b28a)

**Comment by yj-song131** [comment]
저도 딥러닝 이미지 관련 공부하다가 한번 훑어본 논문인데 반갑네요! 정리 감사합니다 ㅎㅎ
