### ISSUE TITLE
MediaPipe: A Framework for Building Perception Pipelines

### ISSUE THREAD

**Issue by minha62** [GDSC-Ewha-4th/Study-paperReview#58]
![image](https://user-images.githubusercontent.com/71062967/202908032-fefbd6e4-5d51-42f4-b711-c3aa1ad28ea3.png)

`MediaPipe`
- a framework for building pipelines to perform inference over arbitrary sensory data
- designed for machine learning practitioners
- the main use case: rapid prototyping of perception pipelines with inference models and other reusable components
- facilitates the deployment of perception technology into demos and applications on a wide variety of different hardware platforms
- enables incremental improvements to perception pipelines

`Three main parts of MediaPipe`
1. a framework for inference from sensory data
2. a set of tools for performance evaluation
3. a collection of reusable inference and processing components called calculators

**Comment by Soyeon-Cha** [comment]
컴퓨터비전 논문을 읽을 때 관련 내용이 나오면 참고할게요! 리뷰 읽고 MediaPipe가 뭔지 알게 됐어요. 감사합니다 :)
