### ISSUE TITLE
UNet++ : A Nested U-Net Architecture for Medical Image Segmentation

### ISSUE THREAD

**Issue by yj-song131** [GDSC-Ewha-4th/Study-paperReview#61]
**Abstract**
* UNet++는 medical image segmentation을 위한 더욱 강력한 architecture이다.
* UNet++가 U-Net과 다른 점은 re-designed skip pathways를 설계하였다는 것이다.
* 이는 encoder와 decoder feature map 사이의 semantic gap을 줄여 optimizer가 더 쉽고 빠르게 학습되는 것이다.

**Introduction**
* Segmentation에 사용되는 U-Net이나 Fully Connected Network의 공통점은 skip connection이다. 이는 complex background에서 fine-grained detail을 얻는 데도 유용하고, 가려져 있는 물체를 segmentation하는 데에도 좋다.
* 그러나 medical image의 특성상 작은 오류도 크게 작용할 수 있다. 그래서 더 fine detail을 얻는 architecture에 집중하였다.  

**U-Net++의 Architecture**
![IMG_0381](https://user-images.githubusercontent.com/97579755/203232399-d5e5a2f7-ba90-4480-959c-02a7b36e3a26.jpg)
* (a) 그림을 보면 encoder와 decoder가 nested dense convolution block으로 연결되어 있다는 것을 알 수 있다.
* (b) 그림은 first skip pathwat의 자세한 과정이다.
* (c) 그림은 UNet++이 만약 deep supervision에서 train 된다면, inference time에서 pruned(가지치기) 될 수 있다는 것을 의미한다.

**Conclusion**
* 이렇게 UNet++는 re-designed skip connection과 deep supervision을 통해 U-Net이나 wide U-Net보다 더 높은 IoU(Intersection of Union) score를 도출할 수 있다.

**Comment by wrryu09** [comment]
skip connection을 적용해 만든 구조는 정밀도를 요하는 작업에 활용하기 적합하군요! 내용 잘 읽었습니다 !!
